### ISSUE TITLE
Use molecule defined playbook

### ISSUE THREAD

**Issue by dr1s** [RebelCodeBase/testaid#7]
We currently test each of our role individually and the current testaid implementation seems to combine all roles into a playbook, which then will be run on the host.
This creates unnecessary problems if roles are incompatible between each other.

Is it possible to define the playbook which testaid runs when using the `testvars` fixture?
Or better to use the playbook which is defined in the `molecule.yml`?

**Comment by RebelCodeBase** [comment]
Not yet but that‘s an interesting feature.

**Comment by amartin3225** [comment]
+1

**Comment by RebelCodeBase** [comment]
I've made role inclusion configurable, please see updated [README](/RebelCodeBase/testaid/blob/master/README.rst) for details.
